version: 2 # use CircleCI 2.0

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.16.3


# Predefined jobs that going to be used as pipeline's workflow.
jobs:

  # Installing required dependencies
  build:
    <<: *defaults
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # special step to restore the dependency cache
      - restore_cache:
          keys: 
            - v1-dependency-cache-{{ checksum "package.json" }}
            - v1-dependency-cache-

      # Installing dependencies
      - run:
          name: Installing dependencies
          command: npm install

      # special step to save the dependency cache
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules


  # Code style & syntax check
  linting:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Running ESlint
          command: npm run linting


  # Test predefined micro functions
  unit_test:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Running a Unit Test
          command: npm run unit-test


  # Deploying to production
  deploying:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: curl -sSf -X POST "https://api.glitch.com/project/githubImport?authorization=$GLITCH_API_TOKEN&projectId=$GLITCH_PROJECT_ID&repo=klerikdust%2Fanniediscord"




# Pipeline
workflows:
  version: 2
  pipeline:
    jobs:
      # First, installing dependencies.
      - build

      # Check for code style & syntax consistency. Requires build to finish.
      - linting:
          requires:
            - build

      # Once everything is done, time to deploy it to the production.
      - deploying:
          requires:
            - build
            - linting
          filters:
            branches:
              only: master